name: snap2done
description: Snap2Done application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: ^1.1.0
  path_provider: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  camera: ^0.11.1
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.7
  uuid: ^4.3.3
  fl_chart: ^0.65.0
  speech_to_text: ^5.0.0
  app_links: ^3.4.3
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.6
  google_sign_in: ^5.4.0
  url_launcher: ^6.2.5
  flutter_slidable: ^3.0.1
  path: ^1.8.3
  app_settings: ^5.1.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  # Assets section - removed pattern images
  assets:
    - assets/images/
    - assets/sounds/
    - assets/images/google_logo.png
    - assets/images/apple_logo.png

  # Add fonts section for DelargoDTPro
  fonts:
    - family: DelargoDTPro
      fonts:
        - asset: assets/fonts/DelargoDTPro.ttf
